name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for opening an issue! Please recall to apply all relevant labels, a repo admin will follow up shortly"
          pr-message: "Thank you for opening an issue! Please remember to link the relevant issue, creating one if necessary"
