name: PR workflow
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        run: npm install
      - name: ESLint
        run: npm run eslint
      - name: Format
        run: npm run format
